In [1]:
from helper import load_bike_raw
df = load_bike_raw()

In [12]:
# date, hour, rented 뽑아서 출력 -> 상단 3개만
df[['date', 'hour', 'rented']].head(3)
df['functioning'] # No ->운영안함 | Yes 운영함 <- 각각의 sum, mean
off = df[df['functioning'] == 'No']
on = df[df['functioning'] == 'Yes']
print('[sum] off:', off.rented.sum(), 'on:', on.rented.sum())

[sum] off: 0 on: 6172314

In [16]:
# 봄,가을 시간대만 AND 온도가 20~25도 <- 해당 하는 데이터를 뽑을것
# isin([..., ...]), .between(값A, 값B)
result = df[df['season'].isin(['Spring', 'Autumn']) & df['temp'].between(20, 25)]
display(result)

# 대여수가 가장 많았던 상위 5개 시간대를 뽑아보세요
# .nlargest
df.nlargest(5, 'rented')

,date,rented,hour,temp,humidity,wind,visibility,dew_point,solar,rainfall,snowfall,season,holiday,functioning
2485,2018-03-14,789,13,20.9,44,4.7,1795,8.1,2.66,0.0,0.0,Spring,No Holiday,Yes
2486,2018-03-14,878,14,21.1,42,4.3,2000,7.6,2.49,0.0,0.0,Spring,No Holiday,Yes
2487,2018-03-14,1025,15,21.7,39,3.3,1979,7.1,2.09,0.0,0.0,Spring,No Holiday,Yes
2488,2018-03-14,1049,16,21.7,41,3.2,2000,7.8,1.91,0.0,0.0,Spring,No Holiday,Yes
2489,2018-03-14,1325,17,20.5,49,3.5,2000,9.4,1.18,0.0,0.0,Spring,No Holiday,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7814,2018-10-22,1122,14,20.6,30,2.2,839,2.3,1.69,0.0,0.0,Autumn,No Holiday,Yes
7815,2018-10-22,1167,15,20.2,31,1.6,855,2.5,1.25,0.0,0.0,Autumn,No Holiday,Yes
7886,2018-10-25,1192,14,20.6,31,1.4,1562,2.8,1.70,0.0,0.0,Autumn,No Holiday,Yes
7887,2018-10-25,1275,15,20.6,32,1.4,1651,3.3,1.40,0.0,0.0,Autumn,No Holiday,Yes
7888,2018-10-25,1528,16,20.4,32,0.9,1720,3.1,0.84,0.0,0.0,Autumn,No Holiday,Yes

,date,rented,hour,temp,humidity,wind,visibility,dew_point,solar,rainfall,snowfall,season,holiday,functioning
4818,2018-06-19,3556,18,24.1,57,2.9,1301,15.0,0.56,0.0,0.0,Summer,No Holiday,Yes
4866,2018-06-21,3418,18,27.8,43,3.0,1933,14.0,1.35,0.0,0.0,Summer,No Holiday,Yes
4650,2018-06-12,3404,18,24.9,53,3.6,2000,14.6,1.28,0.0,0.0,Summer,No Holiday,Yes
4842,2018-06-20,3384,18,27.0,55,3.1,1246,17.1,1.26,0.0,0.0,Summer,No Holiday,Yes
4458,2018-06-04,3380,18,24.4,48,1.9,1998,12.6,0.56,0.0,0.0,Summer,No Holiday,Yes