In [2]:
from helper import titanic_conn, q
conn = titanic_conn()

In [5]:
sql = '''
SELECT Name, Sex, Age 
from titanic 
where age < 5 and Pclass=1
limit 5
'''
q(conn, sql)

                             Name     Sex   Age
0    Allison, Miss. Helen Loraine  female  2.00
1  Allison, Master. Hudson Trevor    male  0.92
2       Dodge, Master. Washington    male  4.00

In [10]:
sql = '''
SELECT Name, Fare, Sex, Age
from titanic 
order by Fare DESC limit 5
'''
# q(conn, sql)

In [12]:
sql = '''
SELECT DISTINCT Embarked FROM titanic
'''
# q(conn, sql)

In [13]:
sql = '''
SELECT count(*) from titanic
where Name LIKE '%Miss%'
'''
# q(conn, sql)

In [15]:
sql = '''
SELECT count(*) from titanic 
where Embarked in ('C', 'Q')
'''
# q(conn, sql)

In [17]:
sql = '''
SELECT count(*) from titanic 
where Age Between 20 AND 30
'''
q(conn, sql)

   count(*)
0       245

In [ ]:
# 문제1. 가장 나이가 많은 승객의 이름과 나이
# 문제2. 2등 3등석 (Pclass) 의 여성 생존자 수